name: gen_ui_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_ai_toolkit: ^0.1.2
  mix: ^1.4.6
  remix: ^0.0.2+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mix_generator: ^0.3.0
  mix_lint: ^0.1.1
  custom_lint: ^0.6.7
  build_runner: ^2.4.12

flutter:  
  uses-material-design: true