name: fleeting_interface
description: An example presentation for SuperDeck
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.5"
dependencies:
  flutter:
    sdk: flutter
  firebase_app_check: ^0.4.0
  firebase_core: ^4.0.0
  flutter_genui:
    git:
      url: https://github.com/flutter/genui.git
      path: packages/flutter_genui
      ref: c5f3fd5d76ebf572d853d1578973ee53ccb2efa5
  flutter_genui_firebase_ai:
    git:
      url: https://github.com/flutter/genui.git
      path: packages/flutter_genui_firebase_ai
      ref: c5f3fd5d76ebf572d853d1578973ee53ccb2efa5
  gpt_markdown: ^1.1.4
  google_fonts: ^6.3.2
  intl: ^0.20.2
  json_schema_builder:
    git:
      url: https://github.com/flutter/genui.git
      path: packages/json_schema_builder
      ref: c5f3fd5d76ebf572d853d1578973ee53ccb2efa5
  logging: ^1.3.0
  mesh: ^0.5.0
  mix: ^2.0.0-dev.5
  superdeck:
    path: ../../superdeck/packages/superdeck
  remix:
    git:
      url: https://github.com/btwld/remix.git
      ref: main
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  superdeck_cli:
    path: ../../superdeck/packages/cli
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .superdeck/
    - .superdeck/assets/
    - assets/travel_example/travel_images/
    - assets/travel_example/booking_service/
